// automatically generated by the FlatBuffers compiler, do not modify

package ru.gloom.protocol.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class AnalyzeRequest extends Table {
    public static void ValidateVersion() {
        Constants.FLATBUFFERS_25_2_10();
    }

    public static AnalyzeRequest getRootAsAnalyzeRequest(ByteBuffer _bb) {
        return getRootAsAnalyzeRequest(_bb, new AnalyzeRequest());
    }

    public static AnalyzeRequest getRootAsAnalyzeRequest(ByteBuffer _bb, AnalyzeRequest obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static boolean AnalyzeRequestBufferHasIdentifier(ByteBuffer _bb) {
        return __has_identifier(_bb, "GAIQ");
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public AnalyzeRequest __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public String name() {
        int o = __offset(4);
        return o != 0 ? __string(o + bb_pos) : null;
    }

    public ByteBuffer nameAsByteBuffer() {
        return __vector_as_bytebuffer(4, 1);
    }

    public ByteBuffer nameInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 4, 1);
    }

    public long count() {
        int o = __offset(6);
        return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
    }

    public float features(int j) {
        int o = __offset(8);
        return o != 0 ? bb.getFloat(__vector(o) + j * 4) : 0;
    }

    public int featuresLength() {
        int o = __offset(8);
        return o != 0 ? __vector_len(o) : 0;
    }

    public FloatVector featuresVector() {
        return featuresVector(new FloatVector());
    }

    public FloatVector featuresVector(FloatVector obj) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(__vector(o), bb) : null;
    }

    public ByteBuffer featuresAsByteBuffer() {
        return __vector_as_bytebuffer(8, 4);
    }

    public ByteBuffer featuresInByteBuffer(ByteBuffer _bb) {
        return __vector_in_bytebuffer(_bb, 8, 4);
    }

    public static int createAnalyzeRequest(FlatBufferBuilder builder,
                                           int nameOffset,
                                           long count,
                                           int featuresOffset) {
        builder.startTable(3);
        AnalyzeRequest.addFeatures(builder, featuresOffset);
        AnalyzeRequest.addCount(builder, count);
        AnalyzeRequest.addName(builder, nameOffset);
        return AnalyzeRequest.endAnalyzeRequest(builder);
    }

    public static void startAnalyzeRequest(FlatBufferBuilder builder) {
        builder.startTable(3);
    }

    public static void addName(FlatBufferBuilder builder, int nameOffset) {
        builder.addOffset(0, nameOffset, 0);
    }

    public static void addCount(FlatBufferBuilder builder, long count) {
        builder.addInt(1, (int) count, (int) 0L);
    }

    public static void addFeatures(FlatBufferBuilder builder, int featuresOffset) {
        builder.addOffset(2, featuresOffset, 0);
    }

    public static int createFeaturesVector(FlatBufferBuilder builder, float[] data) {
        builder.startVector(4, data.length, 4);
        for (int i = data.length - 1; i >= 0; i--) builder.addFloat(data[i]);
        return builder.endVector();
    }

    public static void startFeaturesVector(FlatBufferBuilder builder, int numElems) {
        builder.startVector(4, numElems, 4);
    }

    public static int endAnalyzeRequest(FlatBufferBuilder builder) {
        int o = builder.endTable();
        builder.required(o, 4);  // name
        builder.required(o, 8);  // features
        return o;
    }

    public static void finishAnalyzeRequestBuffer(FlatBufferBuilder builder, int offset) {
        builder.finish(offset, "GAIQ");
    }

    public static void finishSizePrefixedAnalyzeRequestBuffer(FlatBufferBuilder builder, int offset) {
        builder.finishSizePrefixed(offset, "GAIQ");
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public AnalyzeRequest get(int j) {
            return get(new AnalyzeRequest(), j);
        }

        public AnalyzeRequest get(AnalyzeRequest obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

