// automatically generated by the FlatBuffers compiler, do not modify

package ru.gloom.protocol.flatbuffers;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class AnalyzeResponse extends Table {
    public static void ValidateVersion() {
        Constants.FLATBUFFERS_25_2_10();
    }

    public static AnalyzeResponse getRootAsAnalyzeResponse(ByteBuffer _bb) {
        return getRootAsAnalyzeResponse(_bb, new AnalyzeResponse());
    }

    public static AnalyzeResponse getRootAsAnalyzeResponse(ByteBuffer _bb, AnalyzeResponse obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public static boolean AnalyzeResponseBufferHasIdentifier(ByteBuffer _bb) {
        return __has_identifier(_bb, "GAIR");
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public AnalyzeResponse __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public double probability() {
        int o = __offset(4);
        return o != 0 ? bb.getDouble(o + bb_pos) : 0.0;
    }

    public static int createAnalyzeResponse(FlatBufferBuilder builder,
                                            double probability) {
        builder.startTable(1);
        AnalyzeResponse.addProbability(builder, probability);
        return AnalyzeResponse.endAnalyzeResponse(builder);
    }

    public static void startAnalyzeResponse(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addProbability(FlatBufferBuilder builder, double probability) {
        builder.addDouble(0, probability, 0.0);
    }

    public static int endAnalyzeResponse(FlatBufferBuilder builder) {
        return builder.endTable();
    }

    public static void finishAnalyzeResponseBuffer(FlatBufferBuilder builder, int offset) {
        builder.finish(offset, "GAIR");
    }

    public static void finishSizePrefixedAnalyzeResponseBuffer(FlatBufferBuilder builder, int offset) {
        builder.finishSizePrefixed(offset, "GAIR");
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public AnalyzeResponse get(int j) {
            return get(new AnalyzeResponse(), j);
        }

        public AnalyzeResponse get(AnalyzeResponse obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

